import { TraceInterpreterError } from '../../errors/TraceInterpreterError';

export const PYTHON_ERROR_CODES = {
  PARSE_ERROR: 'PYTHON_PARSE_ERROR',
  ENTRY_FUNCTION_NOT_FOUND: 'PYTHON_ENTRY_FUNCTION_NOT_FOUND',
  UNSUPPORTED_STATEMENT: 'PYTHON_UNSUPPORTED_STATEMENT',
  UNSUPPORTED_EXPRESSION: 'PYTHON_UNSUPPORTED_EXPRESSION',
  RUNTIME_TYPE_ERROR: 'PYTHON_RUNTIME_TYPE_ERROR',
  RETURN_OUTSIDE_FUNCTION: 'PYTHON_RETURN_OUTSIDE_FUNCTION',
  INTERNAL_ERROR: 'PYTHON_INTERNAL_ERROR'
} as const;

// createPythonError moved to createPythonError.ts
